{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import apache_beam as beam\n",
    "from apache_beam.io import ReadFromText\n",
    "from apache_beam.io import WriteToText"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:root:Dataset cs327e-fa2019:temp_dataset_1106c6b80e2e4d759f79e4ca67a60652 does not exist so we will create it as temporary with location=None\n",
      "ERROR:root:Exception at bundle <apache_beam.runners.direct.bundle_factory._Bundle object at 0x7f4a37f1e3b0>, due to an exception.\n",
      " Traceback (most recent call last):\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py\", line 341, in call\n",
      "    finish_state)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py\", line 381, in attempt_call\n",
      "    result = evaluator.finish_bundle()\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py\", line 306, in finish_bundle\n",
      "    bundles = _read_values_to_bundles(reader)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py\", line 293, in _read_values_to_bundles\n",
      "    read_result = [GlobalWindows.windowed_value(e) for e in reader]\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/bigquery.py\", line 674, in __iter__\n",
      "    flatten_results=self.flatten_results):\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/bigquery.py\", line 1066, in run_query\n",
      "    response = self._get_query_results(project_id, job_id, page_token)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/utils/retry.py\", line 180, in wrapper\n",
      "    return fun(*args, **kwargs)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/bigquery.py\", line 814, in _get_query_results\n",
      "    response = self.client.jobs.GetQueryResults(request)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/internal/clients/bigquery/bigquery_v2_client.py\", line 353, in GetQueryResults\n",
      "    config, request, global_params=global_params)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apitools/base/py/base_api.py\", line 722, in _RunMethod\n",
      "    return self.ProcessHttpResponse(method_config, http_response, request)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apitools/base/py/base_api.py\", line 728, in ProcessHttpResponse\n",
      "    self.__ProcessHttpResponse(method_config, http_response, request))\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apitools/base/py/base_api.py\", line 599, in __ProcessHttpResponse\n",
      "    http_response, method_config=method_config, request=request)\n",
      "HttpBadRequestError: HttpError accessing <https://www.googleapis.com/bigquery/v2/projects/cs327e-fa2019/queries/7ddc2b1fa7174da99720c867cc8012cd?alt=json&maxResults=10000>: response: <{'status': '400', 'content-length': '362', 'x-xss-protection': '0', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'server': 'ESF', '-content-encoding': 'gzip', 'cache-control': 'private', 'date': 'Mon, 18 Nov 2019 22:13:37 GMT', 'x-frame-options': 'SAMEORIGIN', 'content-type': 'application/json; charset=UTF-8'}>, content <{\n",
      "  \"error\": {\n",
      "    \"code\": 400,\n",
      "    \"message\": \"Table name \\\"Nomination_Events\\\" cannot be resolved: dataset name is missing.\",\n",
      "    \"errors\": [\n",
      "      {\n",
      "        \"message\": \"Table name \\\"Nomination_Events\\\" cannot be resolved: dataset name is missing.\",\n",
      "        \"domain\": \"global\",\n",
      "        \"reason\": \"invalid\"\n",
      "      }\n",
      "    ],\n",
      "    \"status\": \"INVALID_ARGUMENT\"\n",
      "  }\n",
      "}\n",
      ">\n",
      "\n",
      "WARNING:root:Dataset cs327e-fa2019:temp_dataset_9731826449ed4d08ae92ead01335f252 does not exist so we will create it as temporary with location=None\n",
      "ERROR:root:Exception at bundle <apache_beam.runners.direct.bundle_factory._Bundle object at 0x7f4a37f1e3b0>, due to an exception.\n",
      " Traceback (most recent call last):\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py\", line 341, in call\n",
      "    finish_state)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py\", line 381, in attempt_call\n",
      "    result = evaluator.finish_bundle()\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py\", line 306, in finish_bundle\n",
      "    bundles = _read_values_to_bundles(reader)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py\", line 293, in _read_values_to_bundles\n",
      "    read_result = [GlobalWindows.windowed_value(e) for e in reader]\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/bigquery.py\", line 674, in __iter__\n",
      "    flatten_results=self.flatten_results):\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/bigquery.py\", line 1066, in run_query\n",
      "    response = self._get_query_results(project_id, job_id, page_token)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/utils/retry.py\", line 180, in wrapper\n",
      "    return fun(*args, **kwargs)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/bigquery.py\", line 814, in _get_query_results\n",
      "    response = self.client.jobs.GetQueryResults(request)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/internal/clients/bigquery/bigquery_v2_client.py\", line 353, in GetQueryResults\n",
      "    config, request, global_params=global_params)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apitools/base/py/base_api.py\", line 722, in _RunMethod\n",
      "    return self.ProcessHttpResponse(method_config, http_response, request)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apitools/base/py/base_api.py\", line 728, in ProcessHttpResponse\n",
      "    self.__ProcessHttpResponse(method_config, http_response, request))\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apitools/base/py/base_api.py\", line 599, in __ProcessHttpResponse\n",
      "    http_response, method_config=method_config, request=request)\n",
      "HttpBadRequestError: HttpError accessing <https://www.googleapis.com/bigquery/v2/projects/cs327e-fa2019/queries/65ada40d8f174a89a7095f6a77a72179?alt=json&maxResults=10000>: response: <{'status': '400', 'content-length': '362', 'x-xss-protection': '0', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'server': 'ESF', '-content-encoding': 'gzip', 'cache-control': 'private', 'date': 'Mon, 18 Nov 2019 22:13:40 GMT', 'x-frame-options': 'SAMEORIGIN', 'content-type': 'application/json; charset=UTF-8'}>, content <{\n",
      "  \"error\": {\n",
      "    \"code\": 400,\n",
      "    \"message\": \"Table name \\\"Nomination_Events\\\" cannot be resolved: dataset name is missing.\",\n",
      "    \"errors\": [\n",
      "      {\n",
      "        \"message\": \"Table name \\\"Nomination_Events\\\" cannot be resolved: dataset name is missing.\",\n",
      "        \"domain\": \"global\",\n",
      "        \"reason\": \"invalid\"\n",
      "      }\n",
      "    ],\n",
      "    \"status\": \"INVALID_ARGUMENT\"\n",
      "  }\n",
      "}\n",
      ">\n",
      "\n",
      "WARNING:root:Dataset cs327e-fa2019:temp_dataset_310faf42828f4c4292f4c9e801eff0d7 does not exist so we will create it as temporary with location=None\n",
      "ERROR:root:Exception at bundle <apache_beam.runners.direct.bundle_factory._Bundle object at 0x7f4a37f1e3b0>, due to an exception.\n",
      " Traceback (most recent call last):\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py\", line 341, in call\n",
      "    finish_state)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py\", line 381, in attempt_call\n",
      "    result = evaluator.finish_bundle()\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py\", line 306, in finish_bundle\n",
      "    bundles = _read_values_to_bundles(reader)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py\", line 293, in _read_values_to_bundles\n",
      "    read_result = [GlobalWindows.windowed_value(e) for e in reader]\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/bigquery.py\", line 674, in __iter__\n",
      "    flatten_results=self.flatten_results):\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/bigquery.py\", line 1066, in run_query\n",
      "    response = self._get_query_results(project_id, job_id, page_token)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/utils/retry.py\", line 180, in wrapper\n",
      "    return fun(*args, **kwargs)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/bigquery.py\", line 814, in _get_query_results\n",
      "    response = self.client.jobs.GetQueryResults(request)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/internal/clients/bigquery/bigquery_v2_client.py\", line 353, in GetQueryResults\n",
      "    config, request, global_params=global_params)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apitools/base/py/base_api.py\", line 722, in _RunMethod\n",
      "    return self.ProcessHttpResponse(method_config, http_response, request)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apitools/base/py/base_api.py\", line 728, in ProcessHttpResponse\n",
      "    self.__ProcessHttpResponse(method_config, http_response, request))\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apitools/base/py/base_api.py\", line 599, in __ProcessHttpResponse\n",
      "    http_response, method_config=method_config, request=request)\n",
      "HttpBadRequestError: HttpError accessing <https://www.googleapis.com/bigquery/v2/projects/cs327e-fa2019/queries/9f880b9405414c2e841dd4dffc9ad14c?alt=json&maxResults=10000>: response: <{'status': '400', 'content-length': '362', 'x-xss-protection': '0', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'server': 'ESF', '-content-encoding': 'gzip', 'cache-control': 'private', 'date': 'Mon, 18 Nov 2019 22:13:42 GMT', 'x-frame-options': 'SAMEORIGIN', 'content-type': 'application/json; charset=UTF-8'}>, content <{\n",
      "  \"error\": {\n",
      "    \"code\": 400,\n",
      "    \"message\": \"Table name \\\"Nomination_Events\\\" cannot be resolved: dataset name is missing.\",\n",
      "    \"errors\": [\n",
      "      {\n",
      "        \"message\": \"Table name \\\"Nomination_Events\\\" cannot be resolved: dataset name is missing.\",\n",
      "        \"domain\": \"global\",\n",
      "        \"reason\": \"invalid\"\n",
      "      }\n",
      "    ],\n",
      "    \"status\": \"INVALID_ARGUMENT\"\n",
      "  }\n",
      "}\n",
      ">\n",
      "\n",
      "WARNING:root:Dataset cs327e-fa2019:temp_dataset_f4f70480c92c4aee89f4e046c096f805 does not exist so we will create it as temporary with location=None\n",
      "ERROR:root:Exception at bundle <apache_beam.runners.direct.bundle_factory._Bundle object at 0x7f4a37f1e3b0>, due to an exception.\n",
      " Traceback (most recent call last):\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py\", line 341, in call\n",
      "    finish_state)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py\", line 381, in attempt_call\n",
      "    result = evaluator.finish_bundle()\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py\", line 306, in finish_bundle\n",
      "    bundles = _read_values_to_bundles(reader)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py\", line 293, in _read_values_to_bundles\n",
      "    read_result = [GlobalWindows.windowed_value(e) for e in reader]\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/bigquery.py\", line 674, in __iter__\n",
      "    flatten_results=self.flatten_results):\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/bigquery.py\", line 1066, in run_query\n",
      "    response = self._get_query_results(project_id, job_id, page_token)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/utils/retry.py\", line 180, in wrapper\n",
      "    return fun(*args, **kwargs)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/bigquery.py\", line 814, in _get_query_results\n",
      "    response = self.client.jobs.GetQueryResults(request)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/internal/clients/bigquery/bigquery_v2_client.py\", line 353, in GetQueryResults\n",
      "    config, request, global_params=global_params)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apitools/base/py/base_api.py\", line 722, in _RunMethod\n",
      "    return self.ProcessHttpResponse(method_config, http_response, request)\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apitools/base/py/base_api.py\", line 728, in ProcessHttpResponse\n",
      "    self.__ProcessHttpResponse(method_config, http_response, request))\n",
      "  File \"/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apitools/base/py/base_api.py\", line 599, in __ProcessHttpResponse\n",
      "    http_response, method_config=method_config, request=request)\n",
      "HttpBadRequestError: HttpError accessing <https://www.googleapis.com/bigquery/v2/projects/cs327e-fa2019/queries/38f96d7355814675be45b90731273f9a?alt=json&maxResults=10000>: response: <{'status': '400', 'content-length': '362', 'x-xss-protection': '0', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'server': 'ESF', '-content-encoding': 'gzip', 'cache-control': 'private', 'date': 'Mon, 18 Nov 2019 22:13:44 GMT', 'x-frame-options': 'SAMEORIGIN', 'content-type': 'application/json; charset=UTF-8'}>, content <{\n",
      "  \"error\": {\n",
      "    \"code\": 400,\n",
      "    \"message\": \"Table name \\\"Nomination_Events\\\" cannot be resolved: dataset name is missing.\",\n",
      "    \"errors\": [\n",
      "      {\n",
      "        \"message\": \"Table name \\\"Nomination_Events\\\" cannot be resolved: dataset name is missing.\",\n",
      "        \"domain\": \"global\",\n",
      "        \"reason\": \"invalid\"\n",
      "      }\n",
      "    ],\n",
      "    \"status\": \"INVALID_ARGUMENT\"\n",
      "  }\n",
      "}\n",
      ">\n",
      "\n",
      "ERROR:root:Giving up after 4 attempts.\n",
      "WARNING:root:A task failed with exception: HttpError accessing <https://www.googleapis.com/bigquery/v2/projects/cs327e-fa2019/queries/38f96d7355814675be45b90731273f9a?alt=json&maxResults=10000>: response: <{'status': '400', 'content-length': '362', 'x-xss-protection': '0', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'server': 'ESF', '-content-encoding': 'gzip', 'cache-control': 'private', 'date': 'Mon, 18 Nov 2019 22:13:44 GMT', 'x-frame-options': 'SAMEORIGIN', 'content-type': 'application/json; charset=UTF-8'}>, content <{\n",
      "  \"error\": {\n",
      "    \"code\": 400,\n",
      "    \"message\": \"Table name \\\"Nomination_Events\\\" cannot be resolved: dataset name is missing.\",\n",
      "    \"errors\": [\n",
      "      {\n",
      "        \"message\": \"Table name \\\"Nomination_Events\\\" cannot be resolved: dataset name is missing.\",\n",
      "        \"domain\": \"global\",\n",
      "        \"reason\": \"invalid\"\n",
      "      }\n",
      "    ],\n",
      "    \"status\": \"INVALID_ARGUMENT\"\n",
      "  }\n",
      "}\n",
      ">\n"
     ]
    },
    {
     "ename": "HttpBadRequestError",
     "evalue": "HttpError accessing <https://www.googleapis.com/bigquery/v2/projects/cs327e-fa2019/queries/38f96d7355814675be45b90731273f9a?alt=json&maxResults=10000>: response: <{'status': '400', 'content-length': '362', 'x-xss-protection': '0', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'server': 'ESF', '-content-encoding': 'gzip', 'cache-control': 'private', 'date': 'Mon, 18 Nov 2019 22:13:44 GMT', 'x-frame-options': 'SAMEORIGIN', 'content-type': 'application/json; charset=UTF-8'}>, content <{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Table name \\\"Nomination_Events\\\" cannot be resolved: dataset name is missing.\",\n    \"errors\": [\n      {\n        \"message\": \"Table name \\\"Nomination_Events\\\" cannot be resolved: dataset name is missing.\",\n        \"domain\": \"global\",\n        \"reason\": \"invalid\"\n      }\n    ],\n    \"status\": \"INVALID_ARGUMENT\"\n  }\n}\n>",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m\u001b[0m",
      "\u001b[0;31mHttpBadRequestError\u001b[0mTraceback (most recent call last)",
      "\u001b[0;32m<ipython-input-3-f04e0e5a040c>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     53\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     54\u001b[0m     \u001b[0;31m# write PCollection to a file\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 55\u001b[0;31m     \u001b[0mout_pcoll\u001b[0m \u001b[0;34m|\u001b[0m \u001b[0;34m'Write File'\u001b[0m \u001b[0;34m>>\u001b[0m \u001b[0mWriteToText\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'oscars_output.txt'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/pipeline.pyc\u001b[0m in \u001b[0;36m__exit__\u001b[0;34m(self, exc_type, exc_val, exc_tb)\u001b[0m\n\u001b[1;32m    408\u001b[0m   \u001b[0;32mdef\u001b[0m \u001b[0m__exit__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mexc_type\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mexc_val\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mexc_tb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    409\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mexc_type\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 410\u001b[0;31m       \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait_until_finish\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    411\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    412\u001b[0m   \u001b[0;32mdef\u001b[0m \u001b[0mvisit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvisitor\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/direct_runner.pyc\u001b[0m in \u001b[0;36mwait_until_finish\u001b[0;34m(self, duration)\u001b[0m\n\u001b[1;32m    419\u001b[0m             'DirectRunner does not support duration argument.')\n\u001b[1;32m    420\u001b[0m       \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 421\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_executor\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mawait_completion\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    422\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_state\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mPipelineState\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mDONE\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    423\u001b[0m       \u001b[0;32mexcept\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# pylint: disable=broad-except\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.pyc\u001b[0m in \u001b[0;36mawait_completion\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    396\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    397\u001b[0m   \u001b[0;32mdef\u001b[0m \u001b[0mawait_completion\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 398\u001b[0;31m     \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_executor\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mawait_completion\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    399\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    400\u001b[0m   \u001b[0;32mdef\u001b[0m \u001b[0mshutdown\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.pyc\u001b[0m in \u001b[0;36mawait_completion\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    442\u001b[0m       \u001b[0;32mif\u001b[0m \u001b[0mupdate\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexception\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    443\u001b[0m         \u001b[0mt\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mv\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mupdate\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexc_info\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 444\u001b[0;31m         \u001b[0msix\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreraise\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mt\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mv\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    445\u001b[0m     \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    446\u001b[0m       \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexecutor_service\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mshutdown\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.pyc\u001b[0m in \u001b[0;36mcall\u001b[0;34m(self, state_sampler)\u001b[0m\n\u001b[1;32m    339\u001b[0m                           \u001b[0mstart_state\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    340\u001b[0m                           \u001b[0mprocess_state\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 341\u001b[0;31m                           finish_state)\n\u001b[0m\u001b[1;32m    342\u001b[0m         \u001b[0;32mbreak\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    343\u001b[0m       \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.pyc\u001b[0m in \u001b[0;36mattempt_call\u001b[0;34m(self, metrics_container, side_input_values, start_state, process_state, finish_state)\u001b[0m\n\u001b[1;32m    379\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    380\u001b[0m     \u001b[0;32mwith\u001b[0m \u001b[0mfinish_state\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 381\u001b[0;31m       \u001b[0mresult\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mevaluator\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfinish_bundle\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    382\u001b[0m       \u001b[0mresult\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlogical_metric_updates\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mmetrics_container\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_cumulative\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    383\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.pyc\u001b[0m in \u001b[0;36mfinish_bundle\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    304\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    305\u001b[0m       \u001b[0;32mwith\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_source\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mreader\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mreader\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 306\u001b[0;31m         \u001b[0mbundles\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_read_values_to_bundles\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mreader\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    307\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    308\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mTransformResult\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbundles\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mNone\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.pyc\u001b[0m in \u001b[0;36m_read_values_to_bundles\u001b[0;34m(reader)\u001b[0m\n\u001b[1;32m    291\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    292\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_read_values_to_bundles\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mreader\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 293\u001b[0;31m       \u001b[0mread_result\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0mGlobalWindows\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwindowed_value\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0me\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mreader\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    294\u001b[0m       return self._split_list_into_bundles(\n\u001b[1;32m    295\u001b[0m           \u001b[0moutput_pcollection\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mread_result\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/bigquery.pyc\u001b[0m in \u001b[0;36m__iter__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    672\u001b[0m         \u001b[0mproject_id\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexecuting_project\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mquery\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mquery\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    673\u001b[0m         \u001b[0muse_legacy_sql\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0muse_legacy_sql\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 674\u001b[0;31m         flatten_results=self.flatten_results):\n\u001b[0m\u001b[1;32m    675\u001b[0m       \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mschema\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    676\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mschema\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mschema\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/bigquery.pyc\u001b[0m in \u001b[0;36mrun_query\u001b[0;34m(self, project_id, query, use_legacy_sql, flatten_results, dry_run)\u001b[0m\n\u001b[1;32m   1064\u001b[0m     \u001b[0mpage_token\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1065\u001b[0m     \u001b[0;32mwhile\u001b[0m \u001b[0mTrue\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1066\u001b[0;31m       \u001b[0mresponse\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_get_query_results\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mproject_id\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mjob_id\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mpage_token\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1067\u001b[0m       \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mresponse\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjobComplete\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1068\u001b[0m         \u001b[0;31m# The jobComplete field can be False if the query request times out\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/utils/retry.pyc\u001b[0m in \u001b[0;36mwrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    178\u001b[0m       \u001b[0;32mwhile\u001b[0m \u001b[0mTrue\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    179\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 180\u001b[0;31m           \u001b[0;32mreturn\u001b[0m \u001b[0mfun\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    181\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mexn\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# pylint: disable=broad-except\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    182\u001b[0m           \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mretry_filter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mexn\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/bigquery.pyc\u001b[0m in \u001b[0;36m_get_query_results\u001b[0;34m(self, project_id, job_id, page_token, max_results)\u001b[0m\n\u001b[1;32m    812\u001b[0m         \u001b[0mjobId\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mjob_id\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mpageToken\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mpage_token\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mprojectId\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mproject_id\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    813\u001b[0m         maxResults=max_results)\n\u001b[0;32m--> 814\u001b[0;31m     \u001b[0mresponse\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mclient\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjobs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mGetQueryResults\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrequest\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    815\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mresponse\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    816\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apache_beam/io/gcp/internal/clients/bigquery/bigquery_v2_client.pyc\u001b[0m in \u001b[0;36mGetQueryResults\u001b[0;34m(self, request, global_params)\u001b[0m\n\u001b[1;32m    351\u001b[0m       \u001b[0mconfig\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mGetMethodConfig\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'GetQueryResults'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    352\u001b[0m       return self._RunMethod(\n\u001b[0;32m--> 353\u001b[0;31m           config, request, global_params=global_params)\n\u001b[0m\u001b[1;32m    354\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    355\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mInsert\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrequest\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mglobal_params\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mNone\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mupload\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apitools/base/py/base_api.pyc\u001b[0m in \u001b[0;36m_RunMethod\u001b[0;34m(self, method_config, request, global_params, upload, upload_config, download)\u001b[0m\n\u001b[1;32m    720\u001b[0m                 http, http_request, **opts)\n\u001b[1;32m    721\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 722\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mProcessHttpResponse\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmethod_config\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mhttp_response\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrequest\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    723\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    724\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mProcessHttpResponse\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmethod_config\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mhttp_response\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrequest\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apitools/base/py/base_api.pyc\u001b[0m in \u001b[0;36mProcessHttpResponse\u001b[0;34m(self, method_config, http_response, request)\u001b[0m\n\u001b[1;32m    726\u001b[0m         return self.__client.ProcessResponse(\n\u001b[1;32m    727\u001b[0m             \u001b[0mmethod_config\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 728\u001b[0;31m             self.__ProcessHttpResponse(method_config, http_response, request))\n\u001b[0m",
      "\u001b[0;32m/home/jupyter/beam_venv_dir/local/lib/python2.7/site-packages/apitools/base/py/base_api.pyc\u001b[0m in \u001b[0;36m__ProcessHttpResponse\u001b[0;34m(self, method_config, http_response, request)\u001b[0m\n\u001b[1;32m    597\u001b[0m                                              http_client.NO_CONTENT):\n\u001b[1;32m    598\u001b[0m             raise exceptions.HttpError.FromResponse(\n\u001b[0;32m--> 599\u001b[0;31m                 http_response, method_config=method_config, request=request)\n\u001b[0m\u001b[1;32m    600\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mhttp_response\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstatus_code\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mhttp_client\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mNO_CONTENT\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    601\u001b[0m             \u001b[0;31m# TODO(craigcitro): Find out why _replace doesn't seem to work\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mHttpBadRequestError\u001b[0m: HttpError accessing <https://www.googleapis.com/bigquery/v2/projects/cs327e-fa2019/queries/38f96d7355814675be45b90731273f9a?alt=json&maxResults=10000>: response: <{'status': '400', 'content-length': '362', 'x-xss-protection': '0', 'x-content-type-options': 'nosniff', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', 'server': 'ESF', '-content-encoding': 'gzip', 'cache-control': 'private', 'date': 'Mon, 18 Nov 2019 22:13:44 GMT', 'x-frame-options': 'SAMEORIGIN', 'content-type': 'application/json; charset=UTF-8'}>, content <{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Table name \\\"Nomination_Events\\\" cannot be resolved: dataset name is missing.\",\n    \"errors\": [\n      {\n        \"message\": \"Table name \\\"Nomination_Events\\\" cannot be resolved: dataset name is missing.\",\n        \"domain\": \"global\",\n        \"reason\": \"invalid\"\n      }\n    ],\n    \"status\": \"INVALID_ARGUMENT\"\n  }\n}\n>"
     ]
    }
   ],
   "source": [
    "# DoFn to perform on each element in the input PCollection.\n",
    "class ActorCountFn(beam.DoFn):\n",
    "  def process(self, element):\n",
    "    record = element\n",
    "    year = record.get('year')\n",
    "    category = record.get('category')\n",
    "    winner = record.get('winner')\n",
    "    entity = record.get('entity')\n",
    "\n",
    "    if 'ACTOR' in category or 'ACTRESS' in category:\n",
    "        return [(entity, 1)]    \n",
    "\n",
    "# DoFn to perform on each element in the input PCollection.\n",
    "class ActorSumFn(beam.DoFn):\n",
    "  def process(self, element):\n",
    "     actor, count_obj = element # count_obj is an _UnwindowedValues type\n",
    "     count_list = list(count_obj) # cast to list to support len\n",
    "     total_count = len(count_list)\n",
    "     return [(actor, total_count)]  \n",
    "    \n",
    "\n",
    "PROJECT_ID = '<YOUR PROJECT ID>'\n",
    "\n",
    "# Project ID is needed for BigQuery data source, even for local execution.\n",
    "options = {\n",
    "    'project': PROJECT_ID\n",
    "}\n",
    "opts = beam.pipeline.PipelineOptions(flags=[], **options)\n",
    "\n",
    "# Create a Pipeline using a local runner for execution.\n",
    "with beam.Pipeline('DirectRunner', options=opts) as p:\n",
    "\n",
    "    query_string = 'SELECT * FROM Nomination_Events'\n",
    "    query_results = p | 'Read from BigQuery' >> beam.io.Read(beam.io.BigQuerySource(query=query_string))\n",
    "\n",
    "    # write PCollection to log file\n",
    "    query_results | 'Write to log 1' >> WriteToText('query_results.txt')\n",
    "\n",
    "    # apply a ParDo to the PCollection \n",
    "    actor_pcoll = query_results | 'Extract Actor' >> beam.ParDo(ActorCountFn())\n",
    "\n",
    "    # write PCollection to log file\n",
    "    actor_pcoll | 'Write to log 2' >> WriteToText('actor_count.txt')\n",
    "\n",
    "    # apply GroupByKey to the PCollection\n",
    "    group_pcoll = actor_pcoll | 'Group by Actor' >> beam.GroupByKey()\n",
    "\n",
    "    # write PCollection to log file\n",
    "    group_pcoll | 'Write to log 3' >> WriteToText('group_by_actor.txt')\n",
    "  \n",
    "    # apply a ParDo to the PCollection\n",
    "    out_pcoll = group_pcoll | 'Sum up Counts' >> beam.ParDo(ActorSumFn())\n",
    "\n",
    "    # write PCollection to a file\n",
    "    out_pcoll | 'Write File' >> WriteToText('oscars_output.txt')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (beam_venv)",
   "language": "python",
   "name": "beam_venv_kernel"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
